// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface ImportMeta {
	env: {
		AUTH_MAILGUN_KEY: string,
		NEXT_PUBLIC_FIREBASE_API_KEY: string,
		NEXT_PUBLIC_FIREBASE_PROJECT_ID: string,
		NEXT_PUBLIC_FIREBASE_APP_ID: string,
		NEXT_PUBLIC_FIREBASE_VAPID_PUBLIC_KEY: string,
		NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID: string,
		NEXT_PUBLIC_FIREBASE_VAPID_PUBLIC_KEY: string
	}
}

interface CloudflareEnv {
	TEST_DB: D1Database;
}
