// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface ImportMeta {
	env: {
		AUTH_MAILGUN_KEY: string;
	}
}

interface CloudflareEnv {
	TEST_DB: D1Database;
}
